# Stage 1: Build the Rust app
FROM rust:1.80.0-bullseye as builder

# Set the working directory
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y libssl1.1

# Install required dependencies
RUN apt-get update && apt-get install -y pkg-config libssl-dev

# Copy the source code
COPY . .

# Build only the dependencies (this will cache them)
RUN cargo build --release

# Stage 2: Run the Rust app
FROM debian:bookworm-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the built application from the previous stage
COPY --from=builder /usr/src/app/target/release/lineskip-backend .

# Expose the port your application will run on
EXPOSE 8000

# Run the compiled Rust binary, not cargo
CMD ["./lineskip-backend"]