# Stage 1: Build the Rust app
FROM rust:1.80.0-bullseye as builder

# Set the working directory
WORKDIR /usr/src/app

# Copy the Cargo.toml and Cargo.lock first
COPY Cargo.toml Cargo.lock ./

# Build only the dependencies (this will cache them)
RUN cargo build --release

# Stage 2: Run the Rust app
FROM debian:bookworm-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the built application from the previous stage
COPY --from=builder /usr/src/app/target/release/lineskip-backend .

# Expose the port your application will run on
EXPOSE 8000


# Run cargo with a watch command for development
CMD ["cargo", "watch", "-x", "run"]

# Run the compiled Rust binary, not cargo
# CMD ["./lineskip-backend"]